import Navbar from '@/components/navbar/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import Provider from '@/context/AuthContext'
import ToasterContext from '@/context/ToastContext'
import Footer from '@/components/footer/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Blog X - MaleeshaX',
  description: 'Generated by create next app',
}
export const dynamic = 'force-dynamic'
export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <body className={inter.className}>
            <Provider>
              <ToasterContext />
              <Navbar />
              {children}
              <Footer />
            </Provider>
        </body>
    </html>
  )
}
